---
- hosts: localhost
  become: true
  connection: local
  vars:
  roles:
  tasks:
    - name: Updating APK Cache
      apk:
        update_cache: yes

    - name: setting Alpine facts
      set_fact:
        nginx_log_dir: "/var/log/nginx"
        nginx_web_group: "nginx"
        nginx_web_owner: "nginx"
        nginx_web_root: "/var/www/localhost/htdocs"
      when: ansible_os_family == "Alpine"

    - name: setting PHP version
      set_fact:
        php_path: 'etc/php5'  #no leading / for template path
        php_ver: 5
      when: ansible_os_family == 'Alpine'

    - name: Installing PHP-{{ php_ver }}
      apk:
        name: "{{ item }}"
        state: "present"
      with_items:
        - 'php{{ php_ver }}'
        - 'php{{ php_ver }}-cli'
        - 'php{{ php_ver }}-fpm'
      when: nginx_enable_php == 'true'

    - name: Ensuring /var/run/php Exists
      file:
        path: "/var/run/php"
        state: "directory"
      when: nginx_enable_php == 'true'

    - name: Configuring NGINX
      template:
        src: "/nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"

    - name: Configuring NGINX Default Site
      template:
        src: "/default.conf.j2"
        dest: "/etc/nginx/conf.d/default.conf"

    - name: Configuring SupervisorD
      template:
        src: "/supervisord.ini.j2"
        dest: "/etc/supervisor.d/supervisord.ini"
