---
- hosts: localhost
  become: true
  connection: local
  vars:
  roles:
  tasks:
    - name: Updating APK Cache
      apk:
        update_cache: yes

    - name: Installing ca-certificates
      apk:
        name: "ca-certificates"
        state: "present"

    - name: Installing Pre-Reqs
      apk:
        name: "{{ item }}"
        state: "present"
      with_items:
        - 'rsyslog'
        - 'supervisor'

    - name: setting PHP version
      set_fact:
        php_path: 'etc/php5'  #no leading / for template path
        php_ver: 5
      when: ansible_os_family == 'Alpine'

    - name: Installing NGINX
      apk:
        name: "nginx"
        state: "present"

    - name: Installing PHP-{{ nginx_php_ver }}
      apk:
        name: "{{ item }}"
        state: "present"
        install_recommends: no
      with_items:
        - 'php{{ php_ver }}'
        - 'php{{ php_ver }}-cli'
        - 'php{{ php_ver }}-fpm'
      when: nginx_enable_php == 'true'

    - name: Ensuring /var/run/php Exists
      file:
        path: "/var/run/php"
        state: "directory"
      when: nginx_enable_php == 'true'

    - name: Ensuring Folders exist
      file:
        path: "{{ item }}"
        state: "directory"
      with_items:
        - '/run/nginx'
